<?php

namespace MagnetosCompany\BlogBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPosts()
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.categories = :cat')
            ->setParameter('cat', '37')
            ->getQuery();

        return $query;
    }
}
