<?php

namespace MagnetosCompany\BlogBundle\Repository;

use MagnetosCompany\BlogBundle\Entity\Category;
use MagnetosCompany\BlogBundle\Entity\Tag;
use MagnetosCompany\BlogBundle\Entity\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByLastId()
    {
        $query = $this->createQueryBuilder('p')
            ->orderBy('p.id', 'DESC')
            ->setMaxResults(1)
            ->getQuery();

        return $query;
    }

    public function findByFirstId()
    {
        $query = $this->createQueryBuilder('p')
            ->orderBy('p.id', 'ASC')
            ->setMaxResults(1)
            ->getQuery();

        return $query;
    }

    public function findByCategory($id)
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.categories = :category')
            ->setParameter('category', $id)
            ->getQuery();

        return $query;
    }

    public function findByTag($id)
    {
        $query = $this->createQueryBuilder('p')
            ->leftJoin('p.tags', 'tg')
            ->where('tg.id = :tag')
            ->setParameter('tag', $id)
            ->getQuery();

        return $query;
    }

    public function search($word) {
        $query = $this->createQueryBuilder('p')
            ->where('p.title LIKE :word')
            ->setParameter('word', '%'.$word.'%')
            ->getQuery();

        return $query;
    }

}



