blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }

blog_admin:
    path:     /admin
    defaults: { _controller: BlogBundle:Default:admin }

blog_login:
    path:     /login
    defaults: { _controller: BlogBundle:Security:login }

blog_logout:
    path:     /logout
    defaults: { _controller: BlogBundle:Security:logout }


blog_exp:
    path:     /exp
    defaults: { _controller: BlogBundle:Default:exp }

blog_add_user:
    path:     /add_user
    defaults: { _controller: BlogBundle:Default:addUser }

blog_add_post:
    path:     /add_post
    defaults: { _controller: BlogBundle:Default:addPost }

task_success:
    path:     /success
    defaults: { _controller: BlogBundle:Default:success}

