blog_homepage:
    path:     /{_locale}
    defaults: { _controller: BlogBundle:Default:index, _locale: ru }
    requirements:
        _locale: uk|en|ru

blog_admin:
    path:     /admin
    defaults: { _controller: BlogBundle:Default:admin }

blog_login:
    path:     /login
    defaults: { _controller: BlogBundle:Security:login }

blog_logout:
    path:     /logout
    defaults: { _controller: BlogBundle:Security:logout }

blog_exp:
    path:     /exp
    defaults: { _controller: BlogBundle:Default:exp }

blog_register:
    path:     /register
    defaults: { _controller: BlogBundle:User:register }

blog_add_post:
    path:     /add_post
    defaults: { _controller: BlogBundle:Default:addPost }

task_success:
    path:     /success
    defaults: { _controller: BlogBundle:Default:success}

blog_article:
    path:     /{_locale}/article/{id}
    defaults: {_controller: BlogBundle:Default:article, id: 1 }
    requirements:
            _locale: uk|en|ru

blog_category:
    path:    /category/{id}
    defaults: {_controller: BlogBundle:Default:category, id:1}

blog_tag:
    path:    /tag/{id}
    defaults: {_controller: BlogBundle:Default:tag, id:1}



