blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

blog_api:
    resource: "@BlogBundle/Controller/Api"
    type:     annotation

# config/routes/sonata_admin.yaml

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin



