# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_users:
            #entity: { class: MagnetosCompany\BlogBundle\Entity\User, property: email }
            entity:
                class: MagnetosCompany\BlogBundle\Entity\User
                property: email

    encoders:
        MagnetosCompany\BlogBundle\Entity\User: bcrypt


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.security.login_form_authenticator
            logout:
                path: /logout




    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
