# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false


    EntityManager:
        class: Doctrine\ORM\EntityManager

    app.security.login_form_authenticator:
        class: MagnetosCompany\BlogBundle\Security\LoginFormAuthenticator

    app.doctrine.hash_password_listener:
            class: MagnetosCompany\BlogBundle\Doctrine\HashPasswordListener
            tags:
                - { name: doctrine.event_subscriber }

    MessageGenerator:
        class: MagnetosCompany\BlogBundle\Service\MessageGenerator
        public: true

    admin.category:
            class: MagnetosCompany\BlogBundle\Admin\PostAdmin
            arguments: [~, MagnetosCompany\BlogBundle\Entity\Post, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Post }
            public: true



